### PR TITLE
Piping refactor

### PR DESCRIPTION
**Pull request by TheOnAndOnlyZenomat**
This PR can be merged on its own, but if it is not wanted, take a look at the previous one.
This PR introduces everything the previous does, but also a piping refactor.
It now allows to pipe more than two commands, as well as builtins with the same function and therefore streamlines the process a bit and simplifies the code.
For information, take a look at the commit descriptions and feel free to ask me.

### CODE REVIEW

**Comment by Phate6660** [comment]
Oh my god. This PR... it's so beautiful. Every PR you make impresses me more and more.
So I just finished doing some testing. 
It's almost completely flawless, one thing I found however is that echo doesn't output anything for some reason.
It works when piping, it even works when running with `crusty -c "echo example"`, however running it interactively outputs nothing.

**Comment by Phate6660** [comment]
Another thing I noticed, I can't pipe output from `calc`.
It panics with `ParseIntError` in `src/shared_functions.rs:144:55`.
That would make it this line:
```rust
let first_number: i32 = problem_vector[0].parse().unwrap();
```
In `get_calc_vars()`.

**Comment by TheOnAndOnlyZenomat** [comment]
> Oh my god. This PR... it's so beautiful. Every PR you make impresses me more and more.
> So I just finished doing some testing.
> It's almost completely flawless, one thing I found however is that echo doesn't output anything for some reason.
> It works when piping, it even works when running with `crusty -c "echo example"`, however running it interactively outputs nothing.

Thanks^^ Tho I think, that anybody with a bit more rust skills will flame my code^^
I got fixes for both problems lined up, and will probably push them now, or tomorrow.
I thought I tested those cases, but maybe I did that on a different code revision. I am not sure, what cause the echo bug (it has something to do with println!() vs. print!()) I will figure that out hopefully, the calc bug was, because I just forgot to add the piping code to the function.

**Comment by Phate6660** [comment]
> what cause the echo bug
I know. Take a look at line 85 in src/main.rs.
You need it after print statements.

**Comment by TheOnAndOnlyZenomat** [comment]
Yeah, tried that in the ShellCommand::run() match-statement, didn't change it. Will take a closer look at that tomorrow. But otherwise those bugs should be fixed with that commit

**Comment by Phate6660** [comment]
I'll merge this and change to println.
Thank you for this PR! Really good work. :D

**Pull request merged**
