### PR TITLE
Dynamic Prompt

### PR DESCRIPTION
**Pull request by TheOnAndOnlyZenomat**
This implements a dynamic prompt, it can be set via the PROMPT variable. Implementing reading it from the config file should be as trivial as using the config file parser to initialize ShellState.
The dynamic prompt can be used by delimiting the parts, that should be evaluated with `%E`.
For more information see the commit description.

### CODE REVIEW

**Comment by Phate6660** [comment]
Looking really good!
Busy currently, but when I'm free I want to test it a bit before merging.

**Comment by TheOnAndOnlyZenomat** [comment]
No problem, take your time

**Comment by Phate6660** [comment]
I just tested it. It's quite nice!
I'll merge it. I can see some areas of expansion with it, 
so I'll add more features to the prompt in a follow up PR if you don't mind.
For example:
- convenient variables for common info, such as:
  + date
  + time
  + user
  + host (and other network info maybe?)
  + git info if in a repo
  + current directory (with full path or directory name options)
  + etc
- piped commands support
- reading from a file and displaying in prompt

**Comment by Phate6660** [comment]
I thought about `cat`, but I figured we could read from a file through Rust for performance.
And about the branch, I've been thinking.
Honestly you contribute so much to this repo, I'm going to add you as a contributor to the repo that way you commit access to this repo without having to work on a fork.
This will also allow us to work together on features easier.

**Pull request merged**
