### PR TITLE
add "-" support to cd

### PR DESCRIPTION
**Pull request by TheOnAndOnlyZenomat**
Just a small contribution, because I had a bit of time this afternoon.
If there is anything in this PR, that doesn't work with the project, whether the contribution guidelines or codestyle, let me know.

### CODE REVIEW

**Comment by Phate6660** [comment]
Sorry about the wait, I've been working on a new distro setup.

So uh, this is kind of awkward. It's my fault, I probably worded it weird.
By 'previous directory', I meant the previous directory you cd'd into.
For example:
```bash
cd example 1
cd ../example2
cd - # changes to ../example1
```
It's a functionality I use a lot in bash's cd.

**Comment by TheOnAndOnlyZenomat** [comment]
Not weird at all, makes a lot of sense. For parent dir we have `cd ..`. Oh well^^ I'll give that a try then, if you don't mind.

**Comment by Phate6660** [comment]
Go for it, it'd be much appreciated. :D

Once I finish setting up this distro, I'm going to be multitasking a lot of stuff.
So any contributions are welcome!

Oh and one more thing, I public domain everything. So you'll have to be comfortable with public domaining your contributions.

**Comment by TheOnAndOnlyZenomat** [comment]
No problem with the public domain thing.
I am in the process of learning Rust, so if I do anything wrong regarding code, don't hesitate to point it out.

**Pull request closed without merging**
